//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PannelloCharger {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringheColonneTabelle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringheColonneTabelle() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PannelloCharger.Resources.StringheColonneTabelle", typeof(StringheColonneTabelle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cliente.
        /// </summary>
        internal static string ListaApp01Cliente {
            get {
                return ResourceManager.GetString("ListaApp01Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ID Batt..
        /// </summary>
        internal static string ListaApp02IdBatt {
            get {
                return ResourceManager.GetString("ListaApp02IdBatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Batteria.
        /// </summary>
        internal static string ListaApp03Batt {
            get {
                return ResourceManager.GetString("ListaApp03Batt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modello.
        /// </summary>
        internal static string ListaApp04Mod {
            get {
                return ResourceManager.GetString("ListaApp04Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Note.
        /// </summary>
        internal static string ListaApp05Note {
            get {
                return ResourceManager.GetString("ListaApp05Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ID SPY-BATT.
        /// </summary>
        internal static string ListaApp06IdSb {
            get {
                return ResourceManager.GetString("ListaApp06IdSb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a S.N..
        /// </summary>
        internal static string ListaApp07SN {
            get {
                return ResourceManager.GetString("ListaApp07SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Setup.
        /// </summary>
        internal static string ListaSetup01Id {
            get {
                return ResourceManager.GetString("ListaSetup01Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data Creazione.
        /// </summary>
        internal static string ListaSetup02Data {
            get {
                return ResourceManager.GetString("ListaSetup02Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a V def.
        /// </summary>
        internal static string ListaSetup03Vdef {
            get {
                return ResourceManager.GetString("ListaSetup03Vdef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ah def.
        /// </summary>
        internal static string ListaSetup04Adef {
            get {
                return ResourceManager.GetString("ListaSetup04Adef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string ListaSetup05Type {
            get {
                return ResourceManager.GetString("ListaSetup05Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Celle Tot.
        /// </summary>
        internal static string ListaSetup06TCell {
            get {
                return ResourceManager.GetString("ListaSetup06TCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Celle V3.
        /// </summary>
        internal static string ListaSetup07Cel3 {
            get {
                return ResourceManager.GetString("ListaSetup07Cel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Celle V2.
        /// </summary>
        internal static string ListaSetup08Cel2 {
            get {
                return ResourceManager.GetString("ListaSetup08Cel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Celle V1.
        /// </summary>
        internal static string ListaSetup09Cel1 {
            get {
                return ResourceManager.GetString("ListaSetup09Cel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
