//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PannelloCharger {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringheComuni {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringheComuni() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PannelloCharger.Resources.StringheComuni", typeof(StringheComuni).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apro il collegamento.
        /// </summary>
        internal static string AproCollegamento {
            get {
                return ResourceManager.GetString("AproCollegamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caricamento Memoria Dati.
        /// </summary>
        internal static string AvTitolo01Dati {
            get {
                return ResourceManager.GetString("AvTitolo01Dati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caricamento Riepilogo Fasi.
        /// </summary>
        internal static string AvTitolo02Lunghi {
            get {
                return ResourceManager.GetString("AvTitolo02Lunghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caricamento Dettaglio Fasi.
        /// </summary>
        internal static string AvTitolo03Brevi {
            get {
                return ResourceManager.GetString("AvTitolo03Brevi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiornamento Firmware.
        /// </summary>
        internal static string AvTitolo04Firmware {
            get {
                return ResourceManager.GetString("AvTitolo04Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancellazione Memoria.
        /// </summary>
        internal static string CancellaMemoria {
            get {
                return ResourceManager.GetString("CancellaMemoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vuoi veramente azzerare la memoria ?.
        /// </summary>
        internal static string CancellaMemoriaR1 {
            get {
                return ResourceManager.GetString("CancellaMemoriaR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ATTENZIONE: l&apos;operazione cancellerà anche tutti i dati archiviati.
        /// </summary>
        internal static string CancellaMemoriaR2 {
            get {
                return ResourceManager.GetString("CancellaMemoriaR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codice non valido:  Codice non corretto.
        /// </summary>
        internal static string CancellaMemoriaR3 {
            get {
                return ResourceManager.GetString("CancellaMemoriaR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codice non valido:  Dati richiesta non aggiornati.
        /// </summary>
        internal static string CancellaMemoriaR4 {
            get {
                return ResourceManager.GetString("CancellaMemoriaR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codice non valido:  Dispositivo non corrispondente.
        /// </summary>
        internal static string CancellaMemoriaR5 {
            get {
                return ResourceManager.GetString("CancellaMemoriaR5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carica.
        /// </summary>
        internal static string Carica {
            get {
                return ResourceManager.GetString("Carica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carica Dati.
        /// </summary>
        internal static string CaricaDati {
            get {
                return ResourceManager.GetString("CaricaDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configurazione non riuscita.
        /// </summary>
        internal static string CfgFallita {
            get {
                return ResourceManager.GetString("CfgFallita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a collegato alla porta.
        /// </summary>
        internal static string Collegato {
            get {
                return ResourceManager.GetString("Collegato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a collegato alla porta USB.
        /// </summary>
        internal static string CollegatoUSB {
            get {
                return ResourceManager.GetString("CollegatoUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sono già presenti dati relativi all&apos;apparato.
        /// </summary>
        internal static string DatiGiaPresenti {
            get {
                return ResourceManager.GetString("DatiGiaPresenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dati non Validi.
        /// </summary>
        internal static string DatiNonValidi {
            get {
                return ResourceManager.GetString("DatiNonValidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dom.
        /// </summary>
        internal static string Domenica {
            get {
                return ResourceManager.GetString("Domenica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elettrolita.
        /// </summary>
        internal static string Elettrolita {
            get {
                return ResourceManager.GetString("Elettrolita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esporta Dati.
        /// </summary>
        internal static string EsportaDati {
            get {
                return ResourceManager.GetString("EsportaDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esportazione dati Apparato.
        /// </summary>
        internal static string EsportazioneDati {
            get {
                return ResourceManager.GetString("EsportazioneDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Evento Anomalo.
        /// </summary>
        internal static string EventoAnomalo {
            get {
                return ResourceManager.GetString("EventoAnomalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fase di Carica.
        /// </summary>
        internal static string FaseCarica {
            get {
                return ResourceManager.GetString("FaseCarica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fase di Equalizzazione.
        /// </summary>
        internal static string FaseEqualizzazione {
            get {
                return ResourceManager.GetString("FaseEqualizzazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fase di Scarica.
        /// </summary>
        internal static string FaseScarica {
            get {
                return ResourceManager.GetString("FaseScarica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File danneggiato: impossibile caricare i dati.
        /// </summary>
        internal static string FileDanneggiato {
            get {
                return ResourceManager.GetString("FileDanneggiato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File generato.
        /// </summary>
        internal static string FileGenerato {
            get {
                return ResourceManager.GetString("FileGenerato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gio.
        /// </summary>
        internal static string Giovedi {
            get {
                return ResourceManager.GetString("Giovedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Importa Dati.
        /// </summary>
        internal static string ImportaDati {
            get {
                return ResourceManager.GetString("ImportaDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile continuare.
        /// </summary>
        internal static string ImpossibileContinuare {
            get {
                return ResourceManager.GetString("ImpossibileContinuare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni su.
        /// </summary>
        internal static string InformazioniSu {
            get {
                return ResourceManager.GetString("InformazioniSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire un nome valido.
        /// </summary>
        internal static string InserireNome {
            get {
                return ResourceManager.GetString("InserireNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lun.
        /// </summary>
        internal static string Lunedi {
            get {
                return ResourceManager.GetString("Lunedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mar.
        /// </summary>
        internal static string Martedi {
            get {
                return ResourceManager.GetString("Martedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Memoria Cancellata.
        /// </summary>
        internal static string MemoriaCancellata {
            get {
                return ResourceManager.GetString("MemoriaCancellata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mer.
        /// </summary>
        internal static string Mercoledi {
            get {
                return ResourceManager.GetString("Mercoledi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun dispositivo collegato.
        /// </summary>
        internal static string NoDevice {
            get {
                return ResourceManager.GetString("NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apparato Corrente non definito.
        /// </summary>
        internal static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nuova Configurazione.
        /// </summary>
        internal static string NuovaCfg {
            get {
                return ResourceManager.GetString("NuovaCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pausa.
        /// </summary>
        internal static string Pausa {
            get {
                return ResourceManager.GetString("Pausa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pres Elettrolita.
        /// </summary>
        internal static string PresenzaElett {
            get {
                return ResourceManager.GetString("PresenzaElett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vuoi realmente cancellare tutti i dati relativi all&apos;apparato.
        /// </summary>
        internal static string RichConfermaCanc {
            get {
                return ResourceManager.GetString("RichConfermaCanc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sab.
        /// </summary>
        internal static string Sabato {
            get {
                return ResourceManager.GetString("Sabato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva Dati.
        /// </summary>
        internal static string SalvaDati {
            get {
                return ResourceManager.GetString("SalvaDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scarica.
        /// </summary>
        internal static string Scarica {
            get {
                return ResourceManager.GetString("Scarica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configurazione NON ATTIVA.
        /// </summary>
        internal static string StatoPrg00 {
            get {
                return ResourceManager.GetString("StatoPrg00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configurazione ATTIVA; Registrazione NON ATTIVA.
        /// </summary>
        internal static string StatoPrg01 {
            get {
                return ResourceManager.GetString("StatoPrg01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configurazione ATTIVA; Registrazione ATTIVA.
        /// </summary>
        internal static string StatoPrg02 {
            get {
                return ResourceManager.GetString("StatoPrg02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Calibrazione ATTIVA.
        /// </summary>
        internal static string StatoPrg03 {
            get {
                return ResourceManager.GetString("StatoPrg03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stato NON DEFINITO: .
        /// </summary>
        internal static string StatoPrgND {
            get {
                return ResourceManager.GetString("StatoPrgND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configurazione SPY-BATT.
        /// </summary>
        internal static string TitoloCfg {
            get {
                return ResourceManager.GetString("TitoloCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trovato dispositivo.
        /// </summary>
        internal static string TrovatoDispositivo {
            get {
                return ResourceManager.GetString("TrovatoDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ven.
        /// </summary>
        internal static string Venerdi {
            get {
                return ResourceManager.GetString("Venerdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Versione.
        /// </summary>
        internal static string Versione {
            get {
                return ResourceManager.GetString("Versione", resourceCulture);
            }
        }
    }
}
