//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PannelloCharger {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringheMessaggio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringheMessaggio() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PannelloCharger.Resources.StringheMessaggio", typeof(StringheMessaggio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Benvenuto.
        /// </summary>
        internal static string benvenuto {
            get {
                return ResourceManager.GetString("benvenuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a L&apos;operazione comporta la chiusura di tutte le schede aperte..
        /// </summary>
        internal static string ConfermaCambioLingua {
            get {
                return ResourceManager.GetString("ConfermaCambioLingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disconnettere l&apos;utente corrente ?  (L&apos;operazione chiuderà tutte le finestre aperte).
        /// </summary>
        internal static string ConfermaDisconnessione {
            get {
                return ResourceManager.GetString("ConfermaDisconnessione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Versione Firmware non valida o non riconosciuta.
        /// </summary>
        internal static string strFirmwareNonValido {
            get {
                return ResourceManager.GetString("strFirmwareNonValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lun.
        /// </summary>
        internal static string strGiornoLun {
            get {
                return ResourceManager.GetString("strGiornoLun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fase 1 - Invio Testata.
        /// </summary>
        internal static string strMsgAggFWFase1 {
            get {
                return ResourceManager.GetString("strMsgAggFWFase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caricamento Testata Fallito.
        /// </summary>
        internal static string strMsgAggFWFase1err1 {
            get {
                return ResourceManager.GetString("strMsgAggFWFase1err1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fase 2 - Invio Dati.
        /// </summary>
        internal static string strMsgAggFWFase2 {
            get {
                return ResourceManager.GetString("strMsgAggFWFase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caricamento Applicazione fallito ( Blocco Flash 1 ).
        /// </summary>
        internal static string strMsgAggFWFase2err1 {
            get {
                return ResourceManager.GetString("strMsgAggFWFase2err1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caricamento Applicazione fallito ( Blocco Flash 2 ).
        /// </summary>
        internal static string strMsgAggFWFase2err2 {
            get {
                return ResourceManager.GetString("strMsgAggFWFase2err2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caricamento Applicazione fallito ( Blocco Proxy Table ).
        /// </summary>
        internal static string strMsgAggFWFase2err3 {
            get {
                return ResourceManager.GetString("strMsgAggFWFase2err3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fase 3 - Riavvio SPY-BATT.
        /// </summary>
        internal static string strMsgAggFWFase3 {
            get {
                return ResourceManager.GetString("strMsgAggFWFase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiornamento Firmware.
        /// </summary>
        internal static string strMsgAggiornamentoFirmware {
            get {
                return ResourceManager.GetString("strMsgAggiornamentoFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset  SPY-BATT.
        /// </summary>
        internal static string strMsgResetSB {
            get {
                return ResourceManager.GetString("strMsgResetSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata   -   F.C.   -   Opzioni.
        /// </summary>
        internal static string strSottoTitoloPianificazioneTempoBase {
            get {
                return ResourceManager.GetString("strSottoTitoloPianificazioneTempoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata   -   Inizio   -   F.C.   -   Opzioni.
        /// </summary>
        internal static string strSottoTitoloPianificazioneTempoExt {
            get {
                return ResourceManager.GetString("strSottoTitoloPianificazioneTempoExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string strTipoEvento {
            get {
                return ResourceManager.GetString("strTipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dettaglio Fase.
        /// </summary>
        internal static string strTitoloListaBrevi {
            get {
                return ResourceManager.GetString("strTitoloListaBrevi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carica Pianificata.
        /// </summary>
        internal static string strTitoloPianificazione {
            get {
                return ResourceManager.GetString("strTitoloPianificazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fase.
        /// </summary>
        internal static string strVistaLunghiCol01 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo Fase.
        /// </summary>
        internal static string strVistaLunghiCol02 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start .
        /// </summary>
        internal static string strVistaLunghiCol03 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stop.
        /// </summary>
        internal static string strVistaLunghiCol04 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata.
        /// </summary>
        internal static string strVistaLunghiCol05 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a °C Max.
        /// </summary>
        internal static string strVistaLunghiCol06 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a °C Min.
        /// </summary>
        internal static string strVistaLunghiCol06m {
            get {
                return ResourceManager.GetString("strVistaLunghiCol06m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a V Min.
        /// </summary>
        internal static string strVistaLunghiCol07 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a V/El Min.
        /// </summary>
        internal static string strVistaLunghiCol07c {
            get {
                return ResourceManager.GetString("strVistaLunghiCol07c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a V Max.
        /// </summary>
        internal static string strVistaLunghiCol08 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a V/El Max.
        /// </summary>
        internal static string strVistaLunghiCol08c {
            get {
                return ResourceManager.GetString("strVistaLunghiCol08c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I min.
        /// </summary>
        internal static string strVistaLunghiCol09 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I max.
        /// </summary>
        internal static string strVistaLunghiCol10 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stato Elettr..
        /// </summary>
        internal static string strVistaLunghiCol11 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ah.
        /// </summary>
        internal static string strVistaLunghiCol12 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a KWh Totali.
        /// </summary>
        internal static string strVistaLunghiCol13 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a KWh Caricati.
        /// </summary>
        internal static string strVistaLunghiCol13C {
            get {
                return ResourceManager.GetString("strVistaLunghiCol13C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a KWh Scaricati.
        /// </summary>
        internal static string strVistaLunghiCol13S {
            get {
                return ResourceManager.GetString("strVistaLunghiCol13S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a S.o.C..
        /// </summary>
        internal static string strVistaLunghiCol14 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a F.C..
        /// </summary>
        internal static string strVistaLunghiCol15 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Registrazioni.
        /// </summary>
        internal static string strVistaLunghiCol16 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Registrazioni.
        /// </summary>
        internal static string strVistaLunghiCol17 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a max Sbil..
        /// </summary>
        internal static string strVistaLunghiCol20 {
            get {
                return ResourceManager.GetString("strVistaLunghiCol20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ah Caricati.
        /// </summary>
        internal static string strVistaLunghiColAhCaricati {
            get {
                return ResourceManager.GetString("strVistaLunghiColAhCaricati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ah Scaricati.
        /// </summary>
        internal static string strVistaLunghiColAhScaricati {
            get {
                return ResourceManager.GetString("strVistaLunghiColAhScaricati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stop.
        /// </summary>
        internal static string strVistaLunghiColCondStop {
            get {
                return ResourceManager.GetString("strVistaLunghiColCondStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conf.
        /// </summary>
        internal static string strVistaLunghiColIdProgramma {
            get {
                return ResourceManager.GetString("strVistaLunghiColIdProgramma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tempo SovraTemp.
        /// </summary>
        internal static string strVistaLunghiColOverT {
            get {
                return ResourceManager.GetString("strVistaLunghiColOverT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Progressivo Fase.
        /// </summary>
        internal static string strVistaLunghiTtCol01 {
            get {
                return ResourceManager.GetString("strVistaLunghiTtCol01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo Fase.
        /// </summary>
        internal static string strVistaLunghiTtCol02 {
            get {
                return ResourceManager.GetString("strVistaLunghiTtCol02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data/Ora Inizio Fase.
        /// </summary>
        internal static string strVistaLunghiTtCol03 {
            get {
                return ResourceManager.GetString("strVistaLunghiTtCol03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data/Ora Fine Fase.
        /// </summary>
        internal static string strVistaLunghiTtCol04 {
            get {
                return ResourceManager.GetString("strVistaLunghiTtCol04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata Fase.
        /// </summary>
        internal static string strVistaLunghiTtCol05 {
            get {
                return ResourceManager.GetString("strVistaLunghiTtCol05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temperatura Massima.
        /// </summary>
        internal static string strVistaLunghiTtCol06 {
            get {
                return ResourceManager.GetString("strVistaLunghiTtCol06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temperatura Minima.
        /// </summary>
        internal static string strVistaLunghiTtCol06m {
            get {
                return ResourceManager.GetString("strVistaLunghiTtCol06m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tensione Minima.
        /// </summary>
        internal static string strVistaLunghiTtCol07 {
            get {
                return ResourceManager.GetString("strVistaLunghiTtCol07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tensione Massima.
        /// </summary>
        internal static string strVistaLunghiTtCol08 {
            get {
                return ResourceManager.GetString("strVistaLunghiTtCol08", resourceCulture);
            }
        }
    }
}
