//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PannelloCharger {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringheStatistica {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringheStatistica() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PannelloCharger.Resources.StringheStatistica", typeof(StringheStatistica).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Anidride.
        /// </summary>
        internal static string Anidride {
            get {
                return ResourceManager.GetString("Anidride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cicli.
        /// </summary>
        internal static string Cicli {
            get {
                return ResourceManager.GetString("Cicli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CO2 Risparmiata.
        /// </summary>
        internal static string CO2Risparmiata {
            get {
                return ResourceManager.GetString("CO2Risparmiata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Corrente.
        /// </summary>
        internal static string Corrente {
            get {
                return ResourceManager.GetString("Corrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Energia.
        /// </summary>
        internal static string Energia {
            get {
                return ResourceManager.GetString("Energia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Energia Consumata.
        /// </summary>
        internal static string EnergiaConsumata {
            get {
                return ResourceManager.GetString("EnergiaConsumata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fase di Carica.
        /// </summary>
        internal static string FaseCarica {
            get {
                return ResourceManager.GetString("FaseCarica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fase di Scarica.
        /// </summary>
        internal static string FaseScarica {
            get {
                return ResourceManager.GetString("FaseScarica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Assenza.
        /// </summary>
        internal static string GougeAssElr1 {
            get {
                return ResourceManager.GetString("GougeAssElr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elettrolita.
        /// </summary>
        internal static string GougeAssElr2 {
            get {
                return ResourceManager.GetString("GougeAssElr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Cariche.
        /// </summary>
        internal static string GougeCIncr1 {
            get {
                return ResourceManager.GetString("GougeCIncr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parziali.
        /// </summary>
        internal static string GougeCIncr2 {
            get {
                return ResourceManager.GetString("GougeCIncr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string GougeDODr1 {
            get {
                return ResourceManager.GetString("GougeDODr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % D.O.D..
        /// </summary>
        internal static string GougeDODr2 {
            get {
                return ResourceManager.GetString("GougeDODr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Fasi in.
        /// </summary>
        internal static string GougeOverTr1 {
            get {
                return ResourceManager.GetString("GougeOverTr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sovratemp..
        /// </summary>
        internal static string GougeOverTr2 {
            get {
                return ResourceManager.GetString("GougeOverTr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Pause.
        /// </summary>
        internal static string GougePauser1 {
            get {
                return ResourceManager.GetString("GougePauser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Critiche.
        /// </summary>
        internal static string GougePauser2 {
            get {
                return ResourceManager.GetString("GougePauser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Tempo.
        /// </summary>
        internal static string GougeSbilr1 {
            get {
                return ResourceManager.GetString("GougeSbilr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sbil.Celle.
        /// </summary>
        internal static string GougeSbilr2 {
            get {
                return ResourceManager.GetString("GougeSbilr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % S.o.H..
        /// </summary>
        internal static string GougeSOH {
            get {
                return ResourceManager.GetString("GougeSOH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string GougeSOHr1 {
            get {
                return ResourceManager.GetString("GougeSOHr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % S.o.H..
        /// </summary>
        internal static string GougeSOHr2 {
            get {
                return ResourceManager.GetString("GougeSOHr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string GougeSovrar1 {
            get {
                return ResourceManager.GetString("GougeSovrar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Sovrascariche.
        /// </summary>
        internal static string GougeSovrar2 {
            get {
                return ResourceManager.GetString("GougeSovrar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ass.El..
        /// </summary>
        internal static string GrAssenzaElChiave {
            get {
                return ResourceManager.GetString("GrAssenzaElChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Percentuale Assenza Elettrolita sul Numero Fasi.
        /// </summary>
        internal static string GrAssenzaElTitolo {
            get {
                return ResourceManager.GetString("GrAssenzaElTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incr T C.C..
        /// </summary>
        internal static string GrDeltaTCCChiave {
            get {
                return ResourceManager.GetString("GrDeltaTCCChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incremento Temperatura in Carica Completa.
        /// </summary>
        internal static string GrDeltaTCCTitolo {
            get {
                return ResourceManager.GetString("GrDeltaTCCTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incr T C.P..
        /// </summary>
        internal static string GrDeltaTCPChiave {
            get {
                return ResourceManager.GetString("GrDeltaTCPChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incremento Temperatura in Carica Parziale.
        /// </summary>
        internal static string GrDeltaTCPTitolo {
            get {
                return ResourceManager.GetString("GrDeltaTCPTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incr T.S..
        /// </summary>
        internal static string GrDeltaTSChiave {
            get {
                return ResourceManager.GetString("GrDeltaTSChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incremento Temperatura in Scarica.
        /// </summary>
        internal static string GrDeltaTSTitolo {
            get {
                return ResourceManager.GetString("GrDeltaTSTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profondità di Scarica.
        /// </summary>
        internal static string GrDODAsseX {
            get {
                return ResourceManager.GetString("GrDODAsseX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero Cicli.
        /// </summary>
        internal static string GrDODAsseY {
            get {
                return ResourceManager.GetString("GrDODAsseY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a D.o.D..
        /// </summary>
        internal static string GrDODChiave {
            get {
                return ResourceManager.GetString("GrDODChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profondità di Scarica - D.o.D..
        /// </summary>
        internal static string GrDODTitolo {
            get {
                return ResourceManager.GetString("GrDODTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata CC.
        /// </summary>
        internal static string GrDuCCChiave {
            get {
                return ResourceManager.GetString("GrDuCCChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata Cariche Complete.
        /// </summary>
        internal static string GrDuCCTitolo {
            get {
                return ResourceManager.GetString("GrDuCCTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata CP.
        /// </summary>
        internal static string GrDuCPChiave {
            get {
                return ResourceManager.GetString("GrDuCPChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata Cariche Parziali.
        /// </summary>
        internal static string GrDuCPTitolo {
            get {
                return ResourceManager.GetString("GrDuCPTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata (hh:mm).
        /// </summary>
        internal static string GrDurCAsseX {
            get {
                return ResourceManager.GetString("GrDurCAsseX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero Cicli.
        /// </summary>
        internal static string GrDurCAsseY {
            get {
                return ResourceManager.GetString("GrDurCAsseY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ciclo.
        /// </summary>
        internal static string GrSettNotaPunto {
            get {
                return ResourceManager.GetString("GrSettNotaPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temp Max.
        /// </summary>
        internal static string GrSettserTmax {
            get {
                return ResourceManager.GetString("GrSettserTmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temp Media.
        /// </summary>
        internal static string GrSettserTmed {
            get {
                return ResourceManager.GetString("GrSettserTmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temp Min.
        /// </summary>
        internal static string GrSettserTmin {
            get {
                return ResourceManager.GetString("GrSettserTmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Range Temp.
        /// </summary>
        internal static string GrSettserTvar {
            get {
                return ResourceManager.GetString("GrSettserTvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Carica.
        /// </summary>
        internal static string GrSettTitoloAsseY {
            get {
                return ResourceManager.GetString("GrSettTitoloAsseY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incremento Termico.
        /// </summary>
        internal static string GrTempAttivaDelta {
            get {
                return ResourceManager.GetString("GrTempAttivaDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tempertura Massima.
        /// </summary>
        internal static string GrTempAttivaMax {
            get {
                return ResourceManager.GetString("GrTempAttivaMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tempertura Minima.
        /// </summary>
        internal static string GrTempAttivaMin {
            get {
                return ResourceManager.GetString("GrTempAttivaMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grafico Temporale.
        /// </summary>
        internal static string GrTempChiave {
            get {
                return ResourceManager.GetString("GrTempChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tmax C.C..
        /// </summary>
        internal static string GrTmaxCCChiave {
            get {
                return ResourceManager.GetString("GrTmaxCCChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temperature Massime in Carica Completa.
        /// </summary>
        internal static string GrTmaxCCTitolo {
            get {
                return ResourceManager.GetString("GrTmaxCCTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tmax C.P..
        /// </summary>
        internal static string GrTmaxCPChiave {
            get {
                return ResourceManager.GetString("GrTmaxCPChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temperature Massime in Carica Parziale.
        /// </summary>
        internal static string GrTmaxCPTitolo {
            get {
                return ResourceManager.GetString("GrTmaxCPTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a T Max S..
        /// </summary>
        internal static string GrTmaxSChiave {
            get {
                return ResourceManager.GetString("GrTmaxSChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temperature Massime in Scarica.
        /// </summary>
        internal static string GrTmaxSTitolo {
            get {
                return ResourceManager.GetString("GrTmaxSTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a T Min S..
        /// </summary>
        internal static string GrTminSChiave {
            get {
                return ResourceManager.GetString("GrTminSChiave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temperature Minime in Scarica.
        /// </summary>
        internal static string GrTminSTitolo {
            get {
                return ResourceManager.GetString("GrTminSTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inizio Fase.
        /// </summary>
        internal static string InizioFase {
            get {
                return ResourceManager.GetString("InizioFase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero.
        /// </summary>
        internal static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a NumeroCicli.
        /// </summary>
        internal static string NumeroCicli {
            get {
                return ResourceManager.GetString("NumeroCicli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero di Rabbocchi.
        /// </summary>
        internal static string numRabbocchi {
            get {
                return ResourceManager.GetString("numRabbocchi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Carica.
        /// </summary>
        internal static string PercCarica {
            get {
                return ResourceManager.GetString("PercCarica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a % Vita Residua.
        /// </summary>
        internal static string percResidua {
            get {
                return ResourceManager.GetString("percResidua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rabbocchi.
        /// </summary>
        internal static string Rabbocchi_breve {
            get {
                return ResourceManager.GetString("Rabbocchi_breve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settimana.
        /// </summary>
        internal static string Settimana {
            get {
                return ResourceManager.GetString("Settimana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sezione.
        /// </summary>
        internal static string Sezione {
            get {
                return ResourceManager.GetString("Sezione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SoH.
        /// </summary>
        internal static string SoH_breve {
            get {
                return ResourceManager.GetString("SoH_breve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temperatura.
        /// </summary>
        internal static string Temperatura {
            get {
                return ResourceManager.GetString("Temperatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Temperatura Media.
        /// </summary>
        internal static string TemperaturaMedia {
            get {
                return ResourceManager.GetString("TemperaturaMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tensione.
        /// </summary>
        internal static string Tensione {
            get {
                return ResourceManager.GetString("Tensione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tensione per Cella.
        /// </summary>
        internal static string TensionePerCella {
            get {
                return ResourceManager.GetString("TensionePerCella", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tensione Totale.
        /// </summary>
        internal static string TensioneTotale {
            get {
                return ResourceManager.GetString("TensioneTotale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tensioni Parziali in Carica.
        /// </summary>
        internal static string TensioniCarica {
            get {
                return ResourceManager.GetString("TensioniCarica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tensioni Parziali in Scarica.
        /// </summary>
        internal static string TensioniScarica {
            get {
                return ResourceManager.GetString("TensioniScarica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipologia Caricabatteria.
        /// </summary>
        internal static string Tipologia {
            get {
                return ResourceManager.GetString("Tipologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incremento Termico (°C).
        /// </summary>
        internal static string TitAxTDelta {
            get {
                return ResourceManager.GetString("TitAxTDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tempertura Massima (°C).
        /// </summary>
        internal static string TitAxTmax {
            get {
                return ResourceManager.GetString("TitAxTmax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tempertura Minima (°C).
        /// </summary>
        internal static string TitAxTmin {
            get {
                return ResourceManager.GetString("TitAxTmin", resourceCulture);
            }
        }
    }
}
