//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PannelloCharger {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestiProgrammazione {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestiProgrammazione() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PannelloCharger.Resources.TestiProgrammazione", typeof(TestiProgrammazione).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impulsi Riarmo BMS.
        /// </summary>
        public static string chkEqualizzazioneLI {
            get {
                return ResourceManager.GetString("chkEqualizzazioneLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Equalizzazione Finale.
        /// </summary>
        public static string chkEqualizzazionePB {
            get {
                return ResourceManager.GetString("chkEqualizzazionePB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Corrente Minima (A).
        /// </summary>
        public static string lblCorrenteImpLI {
            get {
                return ResourceManager.GetString("lblCorrenteImpLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Corrente Impulso (A).
        /// </summary>
        public static string lblCorrenteImpPB {
            get {
                return ResourceManager.GetString("lblCorrenteImpPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a N° Max Tentativi.
        /// </summary>
        public static string lblNumInpulsiLI {
            get {
                return ResourceManager.GetString("lblNumInpulsiLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a N° Impulsi.
        /// </summary>
        public static string lblNumInpulsiPB {
            get {
                return ResourceManager.GetString("lblNumInpulsiPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tempo Attesa Impulso (s).
        /// </summary>
        public static string lblTAttesaImpulsoLI {
            get {
                return ResourceManager.GetString("lblTAttesaImpulsoLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tempo Attesa iniziale  (m).
        /// </summary>
        public static string lblTAttesaImpulsoPB {
            get {
                return ResourceManager.GetString("lblTAttesaImpulsoPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string lblTDurataImpulsoLI {
            get {
                return ResourceManager.GetString("lblTDurataImpulsoLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata Impulso (m).
        /// </summary>
        public static string lblTDurataImpulsoPB {
            get {
                return ResourceManager.GetString("lblTDurataImpulsoPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata Impulso (s).
        /// </summary>
        public static string lblTempoPausaLI {
            get {
                return ResourceManager.GetString("lblTempoPausaLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tempo Pausa (m).
        /// </summary>
        public static string lblTempoPausaPB {
            get {
                return ResourceManager.GetString("lblTempoPausaPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riarmo BMS.
        /// </summary>
        public static string tabEqualLI {
            get {
                return ResourceManager.GetString("tabEqualLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Equal.
        /// </summary>
        public static string tabEqualPB {
            get {
                return ResourceManager.GetString("tabEqualPB", resourceCulture);
            }
        }
    }
}
